let quotes = [
    '<i>"It’s Not Whether You Get Knocked Down, It’s Whether You Get Up.” ~ Inspirational Quote By Vince Lombardi', 
    '<i>“Creativity Is Intelligence Having Fun.”</i> ~ Albert Einstein',
    '<i>“We Become What We Think About.”</i> ~ Earl Nightingale',
    '<i>“The Person Who Says It Cannot Be Done Should Not Interrupt The Person Who Is Doing It.”</i> ~ Chinese Proverb',
    '<i>“Keep your face always toward the sunshine—and shadows will fall behind you.”</i> ~ Walt Whitman',
    '<i>“Try to be a rainbow in someone’s cloud.”</i> ~ Maya Angelou',
    '<i>“Happiness is not something you postpone for the future; it is something you design for the present.”</i> ~ Jim Rohn',
    '<i>"The great thing in this world is not so much where you stand, as in what direction you are moving."</i> ~ Oliver Wendell Holmes',
    '<i>"If you cannot do great things, do small things in a great way."</i> ~ Napoleon Hill',
    '<i>"Great things are not accomplished by those who yield to trends and fads and popular opinion."</i> ~ Jack Kerouac',
    '<i>"There is a great man who makes every man feel small. But the really great man is the man who makes every man feel great."</i> ~ G. K. Chesterton',
    '<i>"Everybody can be great… because anybody can serve. You don’t have to have a college degree to serve. You don’t have to make your subject and verb agree to serve. You only need a heart full of grace. A soul generated by love."</i> ~ Martin Luther King, Jr.',
    '<i>"You were put on this earth to achieve your greatest self, to live out your purpose, and to do it fearlessly."</i> ~ Steve Maraboli',
    '<i>"Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great."</i> ~ Mark Twain',
    '<i>“You must be the change you wish to see in the world.”</i> ~ Gandhi',
    '<i>“We think sometimes that poverty is only being hungry, naked and homeless. The poverty of being unwanted, unloved and uncared for is the greatest poverty.”</i> ~ Mother Theresa',
    '<i>“If you want happiness for an hour — take a nap. If you want happiness for a day — go fishing. If you want happiness for a year — inherit a fortune. If you want happiness for a life time — help someone else.”</i> ~ Chinese proverb',
    '<i>“Before you diagnose yourself with depression or low self-esteem, first make sure that you are not, in fact, just surrounded by assholes.”</i> ~ Sigmund Freud',
    '<i>"Education is the most powerful weapon which you can use to change the world."</i> ~ Nelson Mandela',
    '<i>"You may not always have a comfortable life and you will not always be able to solve all of the world\'s problems at once but don\'t ever underestimate the importance you can have because history has shown us that courage can be contagious and hope can take on a life of its own."</i> ~ Michelle Obama',
    '<i>“If we find ourselves with a desire that nothing in this world can satisfy, the most probable explanation is that we were made for another world.”</i> ~ C.S. Lewis',
    '<i>“The world is a book and those who do not travel read only one page.”</i> ~ St. Augustine'
]

function newQuote() {
    let randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById("quoteDisplay").innerHTML = quotes[randomNumber];
}